"""add raw ocr fields to receipt

Revision ID: 37937859d941
Revises: 81bb3c115105
Create Date: 2026-07-12 12:55:25.883567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37937859d941'
down_revision: Union[str, Sequence[str], None] = '81bb3c115105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('receipts', sa.Column('supplier_cui', sa.String(), nullable=True))
    op.add_column('receipts', sa.Column('client_cui', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'client_cui')
    op.drop_column('receipts', 'supplier_cui')
    op.drop_column('receipts', 'company_name')
    # ### end Alembic commands ###
