"""make receipt fields nullable add description to items

Revision ID: 81bb3c115105
Revises: 05bcdd6b4ab6
Create Date: 2026-07-11 17:21:37.932436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bb3c115105'
down_revision: Union[str, Sequence[str], None] = '05bcdd6b4ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_items', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('receipts', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('receipts', 'supplier_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('receipts', 'entry_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('receipts', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('receipts', 'time',
               existing_type=sa.TIME(),
               nullable=True)
    op.alter_column('receipts', 'total_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'total_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('receipts', 'time',
               existing_type=sa.TIME(),
               nullable=False)
    op.alter_column('receipts', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('receipts', 'entry_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('receipts', 'supplier_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('receipts', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('receipt_items', 'description')
    # ### end Alembic commands ###
