"""add raw ocr fields to receipt

Revision ID: ed68a2e6b161
Revises: 37937859d941
Create Date: 2026-07-12 23:41:03.045495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed68a2e6b161'
down_revision: Union[str, Sequence[str], None] = '37937859d941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('receipts', sa.Column('validated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('active_client_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'clients', ['active_client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_client_id')
    op.drop_column('receipts', 'validated_at')
    op.drop_column('clients', 'is_deleted')
    # ### end Alembic commands ###
